<?php

abstract class ValidateHandler
{
    public ValidateHandler $nextHandler;
    public function nextHandler(ValidateHandler $handler)
    {
        $this->nextHandler = $handler;
        return $this;
    }

    public function validate(?array $data = null) : void
    {
        if (isset($this->nextHandler) && $this->nextHandler) {
            $this->nextHandler->validate($data);
        }
    }
}

class UserRegisterValidator extends ValidateHandler
{
    public function __construct(
        public string $login,
        public string $email,
        public string $password,
    )
    {
    }

    public function validate(?array $data = null) : void
    {
        if (strlen($this->login) < 3) {
            throw new Exception("For login needs to be at least 3 characters long");
        }
        if (!filter_var($this->email, FILTER_VALIDATE_EMAIL)) {
            throw new Exception("Invalid email address");
        }

        parent::validate($data); // TODO: Change the autogenerated stub
    }
}

class UserPassportValidator extends ValidateHandler
{
    public function __construct(
        public int $seria,
        public int $number,
    )
    {
    }

    public function validate(?array $data = null) : void
    {
        if (strlen($this->seria) < 6) {
            throw new Exception("For serial needs to be at least 6 characters long");
        }

        parent::validate($data); // TODO: Change the autogenerated stub
    }
}

$userRegisterValidator = new UserRegisterValidator($_GET['login'] ?? '', $_GET['email'] ?? '', $_GET['password'] ?? '');

$userRegisterValidator->nextHandler(new UserPassportValidator($_GET['seria'] ?? 0, $_GET['number'] ?? 0));
$userRegisterValidator->validate();